% Funcion matriz de transformacion homogenea de rotacion en X
function H = Hrx(ang)
    dato = whos('ang');
    if strcmp(dato.class, 'sym') % Para variables simbolicas
        H = simplify([1, 0, 0, 0; ...
                      0, cos(ang), -sin(ang), 0; ...
                      0, sin(ang), cos(ang), 0; ...
                      0, 0, 0, 1]);
    else
        theta = deg2rad(ang);
        H = [1, 0, 0, 0; ...
             0, cos(theta), -sin(theta), 0; ...
             0, sin(theta), cos(theta), 0; ...
             0, 0, 0, 1];
    end
end