% Funcion matriz de transformacion homogenea de rotacion en Y
function H = Hry(ang)
    dato = whos('ang');
    if strcmp(dato.class, 'sym') % Para variables simbolicas
        H = simplify([cos(ang), 0, sin(ang), 0; ...
                      0, 1, 0, 0; ...
                      -sin(ang), 0, cos(ang), 0; ...
                      0, 0, 0, 1]);
    else
        theta = deg2rad(ang);
        H = [cos(theta), 0, sin(theta), 0; ...
             0, 1, 0, 0; ...
             -sin(theta), 0, cos(theta), 0; ...
             0, 0, 0, 1];
    end
end