% Funcion matriz de transformacion homogenea de rotacion en Z
function H = Hrz(ang)
    dato = whos('ang');
    if strcmp(dato.class, 'sym') % Para variables simbolicas
        H = simplify([cos(ang), -sin(ang), 0, 0; ...
                      sin(ang), cos(ang), 0, 0; ...
                      0, 0, 1, 0; ...
                      0, 0, 0, 1]);
    else
        theta = deg2rad(ang);
        H = [cos(theta), -sin(theta), 0, 0; ...
             sin(theta), cos(theta), 0, 0; ...
             0, 0, 1, 0; ...
             0, 0, 0, 1];
    end
end