% Funcion matriz de transformacion homogenea de traslacion en Z
function H = Htz(dist)
    dato = whos('dist');
    if strcmp(dato.class, 'sym') % Para variables simbolicas
        H = simplify([1, 0, 0, 0; ...
                      0, 1, 0, 0; ...
                      0, 0, 1, dist; ...
                      0, 0, 0, 1]);
    else
        H = [1, 0, 0, 0; ...
             0, 1, 0, 0; ...
             0, 0, 1, dist; ...
             0, 0, 0, 1];
    end
end